language: python
python:
  - "2.6"
  - "2.7_with_system_site_packages"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
  - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
install: "pip install -r requirements.txt"
# command to run tests
script: py.test
